apiVersion: klot.io/v1
kind: KlotIOApp
metadata:
  name: chore.nandy.io
spec:
  namespace: chore-nandy-io
  description: Chore - Nandy I/O
  manifests:
  - path: kubernetes/namespace.yaml
  - path: api/kubernetes/mysql.yaml
  - path: api/kubernetes/api.yaml
  - path: daemon/kubernetes/daemon.yaml
  - path: gui/kubernetes/gui.yaml
  requires:
  - name: redis.klot.io
    source:
      site: github.com
      repo: klot-io/redis
  - name: mysql.klot.io
    source:
      site: github.com
      repo: klot-io/mysql
  recommends:
  - name: chore-speech.klot.io
    source:
      site: github.com
      repo: nandy-io/chore-speech
      version: gaf3/klot-22-app-settings
  - name: chore-button.klot.io
    source:
      site: github.com
      repo: nandy-io/chore-button
      version: gaf3/klot-21-app-settings
  - name: chore-slack.klot.io
    source:
      site: github.com
      repo: nandy-io/chore-slack
      version: gaf3/klot-19-app-settings
  url:
    protocol: http
    host: www.chore-nandy-io