apiVersion: klot.io/v1
kind: KlotIOApp
metadata:
  name: chore.nandy.io
spec:
  namespace: chore-nandy-io
  group: Nandy I/O
  member: Chore
  description: Tracks chores for people to do
  manifests:
  - path: api/kubernetes/mysql.yaml
  - path: api/kubernetes/api.yaml
  - path: daemon/kubernetes/daemon.yaml
  - path: gui/kubernetes/gui.yaml
  requires:
  - name: redis.klot.io
    source:
      site: github.com
      repo: klot-io/redis
  - name: mysql.klot.io
    source:
      site: github.com
      repo: klot-io/mysql
  - name: people.nandy.io
    source:
      site: github.com
      repo: nandy-io/people
  recommends:
  - name: chore-speech.nandy.io
    source:
      site: github.com
      repo: nandy-io/chore-speech
  - name: chore-button.nandy.io
    source:
      site: github.com
      repo: nandy-io/chore-button
  - name: chore-slack.nandy.io
    source:
      site: github.com
      repo: nandy-io/chore-slack
  - name: chore-google.nandy.io
    source:
      site: github.com
      repo: nandy-io/chore-google
  url:
    protocol: http
    host: www-chore-nandy-io
