apiVersion: klot.io/v1
kind: App
metadata:
  name: chore.nandy.io
  version: v0.1
  description: Chore - Nandy I/O
spec:
  namespace: chore-nandy-io
  manifests:
  - path: kubernetes/namespace.yaml
  - path: api/kubernetes/mysql.yaml
  - path: api/kubernetes/api.yaml
  - path: daemon/kubernetes/daemon.yaml
  - path: gui/kubernetes/gui.yaml
  requires:
  - name: redis.klot.io
    site: github.com
    repo: klot-io/redis
  - name: mysql.klot.io
    site: github.com
    repo: klot-io/mysql
  url: 
    protocol: http
    host: www.chore-nandy-io