apiVersion: klot.io/v1
kind: KlotIOApp
metadata:
  name: chore.nandy.io
spec:
  namespace: chore-nandy-io
  description: Chore - Nandy I/O
  manifests:
  - path: kubernetes/namespace.yaml
  - path: api/kubernetes/mysql.yaml
  - path: api/kubernetes/api.yaml
  - path: daemon/kubernetes/daemon.yaml
  - path: gui/kubernetes/gui.yaml
  requires:
  - name: redis.klot.io
    source:
      site: github.com
      repo: klot-io/redis
  - name: mysql.klot.io
    source:
      site: github.com
      repo: klot-io/mysql
  url:
    protocol: http
    host: www.chore-nandy-io