apiVersion: klot.io/v1
kind: App
metadata:
  name: chore.nandy.io
  description: Chore - Nandy I/O
spec:
  source:
    site: github.com
    repo: nandy-io/chore
  manifests:
  - path: kubernetes/namespace.yaml
  - site: github.com
    repo: nandy-io/chore-daemon
    path: kubernetes/daemon.yaml
  - site: github.com
    repo: nandy-io/chore-api
    path: kubernetes/mysql.yaml
  - site: github.com
    repo: nandy-io/chore-api
    path: kubernetes/api.yaml
  - site: github.com
    repo: nandy-io/chore-gui
    path: kubernetes/gui.yaml
  requires:
  - site: github.com
    repo: klot-io/redis
  - site: github.com
    repo: klot-io/mysql
  - site: github.com
    repo: nandy-io/speech
  url: 
    protocol: http
    host: www.chore-nandy-io